guesses = read.csv("2019_project_data.csv", head=T)
head(guesses)
summary(guesses[,-c(1,4)])
hist(guesses$error, xlab = "Error", ylab = "Frequency", main = "Histogram of Errors")
hist(guesses$abs_error, xlab = "Absolute Error", ylab = "Frequency", main = "Histogram of Absolute Errors")
round(tapply(X=guesses$error, INDEX=guesses$tru_age, FUN = mean), 3)
round(tapply(X=guesses$error, INDEX=guesses$tru_age, FUN = var), 3)
round(tapply(X=guesses$error, INDEX = guesses$sex, FUN = mean), 3)
tapply(X = guesses$error, INDEX = guesses$race, FUN = mean)
tapply(X = guesses$error, INDEX = guesses$race, FUN = var)
boxplot(error ~ tru_age, data = guesses, main = "Boxplot of Error by True Age", xlab = "True Age", ylab = "Error")
boxplot(error ~ sex, data = guesses, main = "Boxplot of Error by Sex", xlab = "Sex", ylab = "Error")
boxplot(error ~ race, data = guesses, main = "Boxplot of Error by Race", xlab = "Race", ylab = "Error")